export default {
  SEARCH_BOOK_START       : 'SEARCH_BOOK_START',
  SEARCH_BEST_OFFER_START : 'SEARCH_BEST_OFFER_START',
  RECEIVE_BOOKS           : 'RECEIVE_BOOKS',
  RECEIVE_BEST_OFFER      : 'RECEIVE_BEST_OFFER',
  RECEIVE_SERVER_ERROR    : 'RECEIVE_SERVER_ERROR',
  ADD_BOOK_TO_CART        : 'ADD_BOOK_TO_CART',
  REMOVE_BOOK_FROM_CART   : 'REMOVE_BOOK_FROM_CART'
};
