export const SEARCH_DISCOUNT_START   = 'SEARCH_DISCOUNT_START';
export const RECEIVE_BOOKS           = 'RECEIVE_BOOKS';
export const RECEIVE_DISCOUNT        = 'RECEIVE_DISCOUNT';
export const RESET_DISCOUNT          = 'RESET_DISCOUNT';
export const RECEIVE_SERVER_ERROR    = 'RECEIVE_SERVER_ERROR';
export const ADD_BOOK_TO_CART        = 'ADD_BOOK_TO_CART';
export const REMOVE_BOOK_FROM_CART   = 'REMOVE_BOOK_FROM_CART';
